<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FB_ProductEjectedState" Id="{826451e0-85d0-40a3-8e88-772e41875071}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL FB_ProductEjectedState IMPLEMENTS I_State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	pMachine : POINTER TO FB_Machine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CustomerTakesCoin" Id="{cfa6fad7-4f8a-4642-ae3e-d6c15280e48f}">
      <Declaration><![CDATA[METHOD CustomerTakesCoin : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="CustomerTakesProduct" Id="{51573c52-7302-419d-ab99-ca7e195cda82}">
      <Declaration><![CDATA[METHOD CustomerTakesProduct : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, 'Customer has taken the product.', '');
pMachine^.SetState(pMachine^.WaitingState);
]]></ST>
      </Implementation>
    </Method>
    <Property Name="Description" Id="{01111630-4049-40c8-930a-71a3140c4d6b}">
      <Declaration><![CDATA[PROPERTY Description : STRING]]></Declaration>
      <Get Name="Get" Id="{5588fee4-402d-4236-86a6-238402fa0410}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Description := 'Product Ejected';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="FB_init" Id="{03f25ce3-0c55-4b1c-95c7-649fcb972492}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	pMachine : POINTER TO FB_Machine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pMachine := pMachine;]]></ST>
      </Implementation>
    </Method>
    <Method Name="InsertCoin" Id="{d9ac4430-7591-4d79-9de2-37f819dcc17e}">
      <Declaration><![CDATA[METHOD InsertCoin : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="PressButton" Id="{434d3a03-36cb-41b1-9115-6c78a3e58fab}">
      <Declaration><![CDATA[METHOD PressButton : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ProductEjectedState">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ProductEjectedState.CustomerTakesCoin">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ProductEjectedState.CustomerTakesProduct">
      <LineId Id="6" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ProductEjectedState.Description.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_ProductEjectedState.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_ProductEjectedState.InsertCoin">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ProductEjectedState.PressButton">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>